version: '3.7'

services:
  echo-server:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "9090:9090"
    networks:
      - oathkeeper-demo
    environment:
      - PORT=9090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  oathkeeper:
    image: oryd/oathkeeper:v0.40.6-distroless
    depends_on:
      - echo-server
    ports:
      - "4456:4456" # API port
    command: serve api -c /etc/config/oathkeeper/config.yaml
    volumes:
      - ./:/etc/config/oathkeeper
    networks:
      - oathkeeper-demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:4456/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  traefik:
    image: traefik:v2.9
    ports:
      - "7000:80"      # HTTP Port (Set header "Host: echo-server" to request)
      # - "8080:8080"  # Admin Port
      # - "443:443"    # HTTPS Port
    command:
      - "--entrypoints.web.address=:80"
      - "--providers.docker"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--accesslog"
    labels:
      - traefik.http.middlewares.oathkeeper.forwardauth.address=http://oathkeeper:4456/decisions 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - oathkeeper-demo

networks:
  oathkeeper-demo:
    driver: bridge
