services:
  echo-server:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "9090:9090"
    networks:
      - oathkeeper-demo
    environment:
      - PORT=9090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  oathkeeper-40-6:
    image: oryd/oathkeeper:v0.40.6
    container_name: oathkeeper-40-6
    depends_on:
      - echo-server
    ports:
      - "7456:4456" # API port
    command: serve api -c /etc/config/oathkeeper/config.yaml
    volumes:
      - ./:/etc/config/oathkeeper
    networks:
      - oathkeeper-demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:4456/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  oathkeeper-40-8:
    image: oryd/oathkeeper:v0.40.8
    container_name: oathkeeper-40-8
    depends_on:
      - echo-server
    ports:
      - "4456:4456" # API port
    command: serve api -c /etc/config/oathkeeper/config.yaml
    volumes:
      - ./:/etc/config/oathkeeper
    networks:
      - oathkeeper-demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:4456/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s


  oathkeeper-40-9:
    image: oryd/oathkeeper:v0.40.9
    container_name: oathkeeper-40-9
    depends_on:
      - echo-server
    ports:
      - "8456:4456" # API port
    command: serve api -c /etc/config/oathkeeper/config.yaml
    volumes:
      - ./:/etc/config/oathkeeper
    networks:
      - oathkeeper-demo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:4456/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  oathkeeper-demo:
    driver: bridge
